export default function AnalysisPanel({ analysis, onReset }) {
  const sections = parseAnalysis(analysis)

  return (
    <div className="flex flex-col h-full">
      {/* Panel header */}
      <div className="px-5 py-4 border-b border-gray-800 shrink-0">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-sm font-semibold">AI Analysis</h2>
            <p className="text-xs text-gray-500 mt-0.5">Powered by Gemini</p>
          </div>
          <button
            onClick={onReset}
            className="px-3 py-1.5 text-xs rounded-lg bg-gray-800 text-gray-400 hover:bg-gray-700 hover:text-white transition-colors"
          >
            New scan
          </button>
        </div>
      </div>

      {/* Analysis content */}
      <div className="flex-1 overflow-y-auto px-5 py-4 space-y-5">
        {sections.length > 0 ? (
          sections.map((section, i) => (
            <Section key={i} {...section} />
          ))
        ) : (
          <PlainText text={analysis} />
        )}
      </div>

      {/* Footer */}
      <div className="px-5 py-3 border-t border-gray-800 shrink-0">
        <p className="text-xs text-gray-600 leading-relaxed">
          This analysis is generated by an AI model and is intended for research purposes only.
          Always consult a qualified neuroradiologist for clinical interpretation.
        </p>
      </div>
    </div>
  )
}

function Section({ title, content, severity }) {
  const color = severity === 'high'
    ? 'border-red-700 bg-red-950/30'
    : severity === 'medium'
    ? 'border-yellow-700 bg-yellow-950/20'
    : 'border-gray-700 bg-gray-900/50'

  return (
    <div className={`rounded-xl border px-4 py-3 ${color}`}>
      {title && (
        <h3 className="text-xs font-semibold uppercase tracking-wider text-gray-400 mb-2">
          {title}
        </h3>
      )}
      <p className="text-sm text-gray-200 leading-relaxed whitespace-pre-wrap">{content}</p>
    </div>
  )
}

function PlainText({ text }) {
  return (
    <div className="rounded-xl border border-gray-700 bg-gray-900/50 px-4 py-3">
      <p className="text-sm text-gray-200 leading-relaxed whitespace-pre-wrap">
        {text || 'No analysis returned.'}
      </p>
    </div>
  )
}

function parseAnalysis(text) {
  if (!text) return []

  const headerPattern = /(?:^|\n)(?:#{1,3}\s+|\*\*|)([A-Z][^*\n]{2,40})(?:\*\*)?:?\s*\n/g
  const matches = [...text.matchAll(headerPattern)]

  if (matches.length < 2) return []

  const sections = []
  for (let i = 0; i < matches.length; i++) {
    const match = matches[i]
    const title = match[1].trim()
    const start = match.index + match[0].length
    const end = i + 1 < matches.length ? matches[i + 1].index : text.length
    const content = text.slice(start, end).trim()

    const lowerTitle = title.toLowerCase()
    const severity =
      lowerTitle.includes('severe') || lowerTitle.includes('critical')
        ? 'high'
        : lowerTitle.includes('moderate') || lowerTitle.includes('warning')
        ? 'medium'
        : 'normal'

    if (content) sections.push({ title, content, severity })
  }

  return sections
}
