"""
models.py — Pydantic response schemas for the analysis API.

Defines the complete data model for GET /analyze/{job_id} and GET /render/{job_id}.
"""

from __future__ import annotations

from typing import Any, Optional
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Step 5a — Stenosis
# ---------------------------------------------------------------------------
class StenosisCandidate(BaseModel):
    """A detected stenosis along an artery segment."""
    artery_name: str
    voxel_coordinates: list[float] = Field(description="[x, y, z] in voxel space")
    mni_coordinates: list[float] = Field(description="[x, y, z] in MNI152 space")
    stenosis_percent: float = Field(description="Stenosis percentage (NASCET)")
    severity: str = Field(description="'normal', 'moderate', or 'severe'")
    affected_segment_length_mm: float
    r_min: float = Field(description="Minimum radius at stenosis site (mm)")
    r_reference: float = Field(description="Reference radius from proximal segment (mm)")


# ---------------------------------------------------------------------------
# Step 5b — Aneurysm
# ---------------------------------------------------------------------------
class AneurysmCandidate(BaseModel):
    """A potential aneurysm detected at or near a bifurcation."""
    artery_name: str
    bifurcation_voxel_coords: list[float]
    mni_coords: list[float]
    size_ratio: float = Field(description="local_max_radius / parent_vessel_radius")
    aspect_ratio: float = Field(description="depth / neck_width")
    deviation_score: float = Field(description="Std deviations from tubular model")
    confidence: str = Field(description="'low', 'moderate', or 'high'")


# ---------------------------------------------------------------------------
# Step 5c — Tortuosity
# ---------------------------------------------------------------------------
class TortuosityResult(BaseModel):
    """Tortuosity metrics for a single artery segment."""
    distance_factor: float = Field(description="Centerline length / Euclidean distance")
    soam: float = Field(description="Sum of Angles Metric (rad/mm)")
    flagged: bool = Field(description="True if DF or SOAM exceeds threshold")


# ---------------------------------------------------------------------------
# Step 5d — Small Vessel Disease
# ---------------------------------------------------------------------------
class SVDResult(BaseModel):
    """Small vessel disease proxy metrics."""
    deep_wm_density: float = Field(description="Vessel density in deep white matter")
    basal_ganglia_density: float = Field(description="Vessel density in basal ganglia")
    cortical_density: float = Field(description="Vessel density in cortical gray matter")
    svd_ratio: float = Field(description="deep_WM_density / cortical_density")
    small_vessel_count: int = Field(description="Skeleton segments with radius < 0.75mm in deep WM")
    svd_flag: bool = Field(description="True if SVD ratio < 0.4 (SVD-suggestive)")


# ---------------------------------------------------------------------------
# Per-artery results container
# ---------------------------------------------------------------------------
class ArteryResult(BaseModel):
    """Complete analysis results for a single named artery."""
    visible: bool = True
    stenosis_candidates: list[StenosisCandidate] = Field(default_factory=list)
    aneurysm_candidates: list[AneurysmCandidate] = Field(default_factory=list)
    tortuosity: Optional[TortuosityResult] = None
    small_vessel_disease: Optional[SVDResult] = None
    # Voxel-level data for GET /analyze binary_segments
    voxel_count: int = 0
    voxel_indices: list[list[int]] = Field(default_factory=list)
    centerline_indices: list[list[int]] = Field(default_factory=list)
    mean_radius_mm: float = 0.0
    segment_length_mm: float = 0.0
    analysis: str = ""


# ---------------------------------------------------------------------------
# Risk scores
# ---------------------------------------------------------------------------
class RiskScore(BaseModel):
    """A rule-based risk score with severity and contributing features."""
    score: float = Field(ge=0, le=100, description="Risk score 0−100")
    severity: str = Field(description="'low', 'moderate', or 'high'")
    drivers: list[str] = Field(
        default_factory=list,
        description="List of features driving this risk score"
    )


# ---------------------------------------------------------------------------
# Gemini report
# ---------------------------------------------------------------------------
class GeminiReport(BaseModel):
    """Report generated by Gemini 1.5 Pro Vision."""
    structured_json: dict[str, Any] = Field(
        default_factory=dict,
        description="Structured findings parsed from Gemini response"
    )
    narrative_summary: str = Field(
        default="",
        description="Plain English clinical narrative summary"
    )


# ---------------------------------------------------------------------------
# Slice image paths
# ---------------------------------------------------------------------------
class SliceImages(BaseModel):
    """Paths to rendered axial and coronal slice PNGs for an artery."""
    axial: str = ""
    coronal: str = ""


# ---------------------------------------------------------------------------
# Top-level analysis response
# ---------------------------------------------------------------------------
class AnalysisResponse(BaseModel):
    """Full internal response stored in _jobs after pipeline completion."""
    job_id: str
    status: str = "complete"
    output_mask_path: str = ""
    overlay_path: str = ""
    mask_shape: list[int] = Field(default_factory=list)
    mask_voxel_size: list[float] = Field(default_factory=list)
    mask_affine: list[list[float]] = Field(default_factory=list)
    vessel_voxel_count: int = 0
    arteries: dict[str, ArteryResult] = Field(default_factory=dict)
    risk_scores: dict[str, RiskScore] = Field(default_factory=dict)
    gemini_report: GeminiReport = Field(default_factory=GeminiReport)
    slice_images: dict[str, SliceImages] = Field(default_factory=dict)
    warnings: list[str] = Field(
        default_factory=list,
        description="Non-fatal warnings (e.g., no GPU, fallback tool used)"
    )
    step_errors: dict[str, str] = Field(
        default_factory=dict,
        description="Per-step error messages for steps that failed"
    )
    disclaimer: str = (
        "This output is generated by a research pipeline and does not "
        "constitute clinical diagnosis."
    )


# ---------------------------------------------------------------------------
# Job status (lightweight for /results polling)
# ---------------------------------------------------------------------------
class JobStatus(BaseModel):
    """Lightweight status returned while job is still processing."""
    job_id: str
    status: str = Field(description="'processing', 'complete', or 'failed'")
    message: str = ""
